server:
  port: 8081

spring:
  artemis:
    # broker 主机
    host: localhost
    # broker 端口
    port: 61616
    #    user: aaa                    # 用于访问 broker 的用户（可选）
    #    password: 123                # 用于访问 broker 的密码（可选）
    embedded:
      enabled: false
    mode: native
